### ISSUE TITLE
Make EL extractor work despite absence of geostreams

### ISSUE THREAD

**Issue by czender** [terraref/extractors-environmental#10]
The EL extractor should workaround the absence of pyclowder.geostreams rather than failing. Please create the appropriate code "try/fail" workarounds.

**Comment by max-zilla** [comment]
@czender the geostream stuff should live in the Clowder extractor anyway - we are using PyClowder2 for this elsewhere. In my latest pull request I move the geostreams code there so you won't see the error from the command line because the geostreams push won't be executed.
