### ISSUE TITLE
Clean up the raw environmental raw data

### ISSUE THREAD

**Issue by FlyingWithJerome** [terraref/extractors-environmental#5]
@dlebauer @max-zilla 

I noticed that there are some duplicated files in the EL raw data folders end with "envionmental.json,"
from the beginning of 2016 to 04/26/2016. I would like to know if anyone with the write access to the project folder can clean them up?
The root directory is
```sh
projects/arpae/terraref/sites/ua-mac/raw_data/EnvironmentLogger/
```

BTW, I would also like to know if the environmental logger extractor is working now so that we can have the Level 1 Environmental Logger data (aka the netCDF outputs)

**Comment by max-zilla** [comment]
@FlyingWithJerome I believe this was due to a typo correction "enviROMentlogger" -> "enviRONMmentlogger" in the filenames. will talk with @jdmaloney about removing.

**Comment by rachelshekar** [comment]
@max-zilla and @jdmaloney  - can this issue be closed?

**Comment by max-zilla** [comment]
@rachelshekar yup
